[options]
addons_path = ./addons;./odoo/addons
data_dir = ./data
db_name = customer_extend_db
admin_passwd = admin
http_port = 8069
logfile = ./odoo_customer.log
log_level = info
test_enable = True
without_demo = True